### ISSUE TITLE
./lib/suggest_grid/configuration.rb:9: syntax error, unexpected tLABEL

### ISSUE THREAD

**Issue by AlanJGarza** [suggestgrid/suggestgrid-ruby#2]
```
./lib/suggest_grid/configuration.rb:9: syntax error, unexpected tLABEL
    @basic_auth_user_name = TODO: Replace
                                 ^
./lib/suggest_grid/configuration.rb:12: syntax error, unexpected tLABEL
    @basic_auth_password = TODO: Replace
```
Your latest commit seems to have broken it by removing the single quote.

https://github.com/suggestgrid/suggestgrid-ruby/commit/09fee17d872974a8ac9096ae3dde3ddc185ca27a#diff-3f4d943bbf5d833a277de882086bf5e3L9

**Comment by emrehan** [comment]
Thank you Alan, I'm going to have a look at this.

**Comment by emrehan** [comment]
Hi @AlanJGarza, I fixed this with https://github.com/suggestgrid/suggestgrid-ruby/commit/ea04d9dc29c26999260759658b6e390bc1fb1856

Does it work for you now?

**Comment by AlanJGarza** [comment]
We've switched to something else. Thanks for the follow up though.

**Comment by emrehan** [comment]
You're welcome
