### ISSUE TITLE
Issue with gem name in documentation

### ISSUE THREAD

**Issue by nlively** [suggestgrid/suggestgrid-ruby#6]
The following recommended line threw an error on `bundle install`:
`gem 'suggest_grid', git: 'https://github.com/suggestgrid/suggestgrid-ruby.git'`

The following did not throw an error:
`gem 'suggestgrid'`

Please update docs

**Comment by hantuzun** [comment]
Hi Noah;

Thank you for pointing out the issue! It's fixed now on [the development branch](https://github.com/suggestgrid/suggestgrid-ruby/tree/development) and it'll be merged to our master branch in this week.

**Comment by johnchambers** [comment]
I noticed the old gem name is referenced in the Heroku documentation also. 

https://devcenter.heroku.com/articles/suggestgrid

**Comment by hantuzun** [comment]
Hi @johnchambers, thank you for pointing out that as well. It's fixed now, the updated documentation is live.
