### ISSUE TITLE
Best practice for unique ratings?

### ISSUE THREAD

**Issue by nlively** [suggestgrid/suggestgrid-ruby#7]
We're endeavoring to ensure that rating is unique per user and content item.

My goal would be to post an action with type=rating, user_id=3, content_id=10, rating=3.7

Then if the user changes their mind and wants to rate it 4.5, the would post another action
type=rating, user_id=3, content_id=10, rating=4.5

Currently I see 2 actions created in the SuggestGrid dashboard when I test this.  How do I set it up so that my second action does an UPDATE rather than a CREATE?

**Comment by ferhatsb** [comment]
Hi @nlively 

While creating models for explicit ratings, latest score is taken into account. We keep all rating information about click stream data, so in future we plan to add insights api and you can analyze user behaviour etc.

Does it sounds OK ?

**Comment by nlively** [comment]
So, to clarify, the Actions table in the dashboard will show ALL actions, but the actual rating used is the latest one given for a particular customer/content pair?

So, given an explicit type of "rate" and the following 2 records...
```
type: rate
userid: 2
itemid: 242
rating: 3.6
timestamp: 1484758901 

type: rate
userid: 2
itemid: 242
rating: 3.8
timestamp: 1484759943 
```  

... only the second one would be used to determine recommendations since it's the latest record?

**Comment by ferhatsb** [comment]
Exactly, latest one would be used according to timestamp value.

**Comment by nlively** [comment]
Great, thanks!

**Comment by hantuzun** [comment]
Hi @nlively,

Thank you for raising this issue. We missed that displaying the actions could have raised such a confusion. I've updated the [actions documentation](http://suggestgrid.com/docs/actions) if anybody else reads there first.
